# Docker compose file
---
version: '3.2'

services:

  #Development Version
  web-development:
    restart: always
    hostname: pithersite-1
    volumes:
      - .:/code
    expose:
      - "8000"

    build: .
    command: >
      bash -c "python /code/testsite/manage.py compilescss
      && python /code/testsite/manage.py collectstatic --ignore=*.scss --noinput
      && python /code/testsite/manage.py runserver 0.0.0.0:8000 --insecure"

  nginx-production:
    restart: always
    build: ./nginx/
    container_name: nginx
    volumes:
      - ./testsite/:/testsite/
      - ./testsite/static/:/static/
      - ~/certs-data/:/data/letsencrypt/
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - web-development
    ports:
      - "80:80"
      - "443:443"
    links:
      - web-development:web-development

  #Production Version
  web-production:
    restart: always
    hostname: pithersite-1
    volumes:
      - .:/code
    expose:
      - "8000"

    image: registry.gitlab.com/pithers/web-work:latest
    command: >
      bash -c "python /code/testsite/manage.py compilescss
      && python /code/testsite/manage.py collectstatic --ignore=*.scss --noinput
      && css-html-js-minify /code/testsite/static
      && uwsgi /code/deployment.ini"

  nginx-production:
    restart: always
    build: ./nginx/
    container_name: nginx
    volumes:
      - ./testsite/:/testsite/
      - ./testsite/static/:/static/
      - ~/certs-data/:/data/letsencrypt/
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - web-production
    ports:
      - "80:80"
      - "443:443"
    links:
      - web-production:web-production
