# Docker compose file
---
version: '3.2'

services:
  web:
    restart: always
    hostname: pithersite-1
    #image: registry.gitlab.com/pithers/web-work:latest
    build: .
    volumes:
      - .:/code
        #ports:
        #- 8000:8000
    expose:
      - "8000"
    #Development Version
    #command: >
    #  bash -c "python /code/testsite/manage.py compilescss
    #  && python /code/testsite/manage.py collectstatic --ignore=*.scss --noinput
    #  && python /code/testsite/manage.py runserver 0.0.0.0:8000 --insecure"
    #Production Version
    command: >
      bash -c "python /code/testsite/manage.py compilescss
      && python /code/testsite/manage.py collectstatic --ignore=*.scss --noinput
      && uwsgi /code/deployment.ini"
    #command: uwsgi /code/deployment.ini

  nginx:
    restart: always
    build: ./nginx/
    container_name: nginx
    volumes:
      - ./testsite/static/:/static/
      - ~/certs-data/:/data/letsencrypt/
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    links:
      - web:web
