# Docker compose file
# Development Version
---
version: '3.2'

services:

  web:
    environment:
      SERVER_MODE: 'development'
    volumes:
      - .:/code
    ports:
      - 8000:8000

    build: .
    command: >
      bash -c "python /code/testsite/manage.py compilescss
      && python /code/testsite/manage.py collectstatic --ignore=*.scss --noinput
      && python /code/testsite/manage.py runserver 0.0.0.0:8000 --insecure"

#  nginx:
#    restart: always
#    build: ./nginx/
#    container_name: nginx
#    volumes:
#      - ./testsite/:/testsite/
#      - ./testsite/static/:/static/
#      - ~/certs-data/:/data/letsencrypt/
#      - /etc/letsencrypt/:/etc/letsencrypt/
#    depends_on:
#      - web
#    ports:
#      - "80:80"
#      - "443:443"
#    links:
#      - web:web
