# Docker compose file
---
version: '3.2'

services:
  web:
    restart: always
    hostname: pithersite-1
    #image: registry.gitlab.com/pithers/web-work:latest
    build: .
    volumes:
      - .:/code
        #ports:
        #- 8000:8000
    expose:
      - "8000"
    command: python /code/testsite/manage.py runserver 0.0.0.0:8000

  nginx:
    restart: always
    build: ./nginx/
    container_name: nginx
    volumes:
      - ~/certs-data/:/data/letsencrypt/
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
#      volumes:
#        - ./code/static:/static
    links:
      - web:web
