# Docker compose file
# Production Version
---
version: '3.2'

services:

  web:
    restart: always
    hostname: pithersite-1
    environment:
      #SECURITY WARNING: Use your own key here
      SECRET_KEY = 'a@mrs3402348hzy0r0t-5%4h*de3y3n4y1lmn1c&ysbmz'
    volumes:
      - .:/code
    expose:
      - "8000"

    image: registry.gitlab.com/pithers/web-work:latest
    command: >
      bash -c "python /code/testsite/manage.py compilescss
      && python /code/testsite/manage.py collectstatic --ignore=*.scss --noinput
      && crass /code/testsite/static/scss/style.css --optimize
      && uwsgi /code/deployment.ini"

  nginx:
    restart: always
    build: ./nginx/
    container_name: nginx
    volumes:
      - ./testsite/:/testsite/
      - ./testsite/static/:/static/
      - ~/certs-data/:/data/letsencrypt/
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    links:
      - web:web
