# Generated by Django 2.1.4 on 2019-01-16 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_scheme_name', models.CharField(max_length=20)),
                ('color_bg', models.CharField(default='#666666', help_text='Please submit valid hexcode, ex: #666666', max_length=7, validators=[myapp.models.validate_color])),
                ('color_text', models.CharField(default='#666666', help_text='Please submit valid hexcode, ex: #666666', max_length=7, validators=[myapp.models.validate_color])),
                ('color_text_invert', models.CharField(default='#666666', help_text='Please submit valid hexcode, ex: #666666', max_length=7, validators=[myapp.models.validate_color])),
                ('color_text_highlight', models.CharField(default='#666666', help_text='Please submit valid hexcode, ex: #666666', max_length=7, validators=[myapp.models.validate_color])),
                ('color_base', models.CharField(default='#666666', help_text='Please submit valid hexcode, ex: #666666', max_length=7, validators=[myapp.models.validate_color])),
                ('color_accent', models.CharField(default='#666666', help_text='Please submit valid hexcode, ex: #666666', max_length=7, validators=[myapp.models.validate_color])),
                ('color_tertiary', models.CharField(default='#666666', help_text='Please submit valid hexcode, ex: #666666', max_length=7, validators=[myapp.models.validate_color])),
                ('color_border', models.CharField(default='#666666', help_text='Please submit valid hexcode, ex: #666666', max_length=7, validators=[myapp.models.validate_color])),
                ('color_border_accent', models.CharField(default='#666666', help_text='Please submit valid hexcode, ex: #666666', max_length=7, validators=[myapp.models.validate_color])),
                ('color_drop_shadow', models.CharField(default='#666666', help_text='Please submit valid hexcode, ex: #666666', max_length=7, validators=[myapp.models.validate_color])),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
